### ISSUE TITLE
pip3 install pennylane_pq fails on osx, dockerhub & ubuntu

### ISSUE THREAD

**Issue by twobombs** [XanaduAI/pennylane-pq#52]
<img width="1326" alt="Screenshot 2019-07-17 at 14 42 10" src="https://user-images.githubusercontent.com/12692227/61376328-4574e300-a8a1-11e9-9b51-083d8da28787.png">

package seems to miss requirements.txt

I could go back to a code build, but the 'pip3 install' is more elegant :)

Saw this happen on OSX and ARM64

**Comment by co9olguy** [comment]
Thanks  @twobombs, we'll have to look into this. Obviously the repo has the `requirements.txt`, so it's not immediately clear what the discrepancy is here

**Comment by twobombs** [comment]
typo in packaging ?

![Screenshot 2019-07-30 at 10 25 09](https://user-images.githubusercontent.com/12692227/62113129-53206480-b2b4-11e9-9c96-910337712bb7.png)

![Screenshot 2019-07-30 at 10 24 08](https://user-images.githubusercontent.com/12692227/62113063-3552ff80-b2b4-11e9-92ba-edb0b957aae6.png)

**Comment by twobombs** [comment]
After copy & rename requires.txt to the root of project filename requirement.txt it builds

![Screenshot 2019-07-30 at 10 31 31](https://user-images.githubusercontent.com/12692227/62113724-6122b500-b2b5-11e9-91a6-9cb6cdd4b738.png)

....  and installs

![Screenshot 2019-07-30 at 10 31 57](https://user-images.githubusercontent.com/12692227/62113722-6122b500-b2b5-11e9-8a2e-87d7f78095df.png)

FYI :)

**Comment by josh146** [comment]
Thanks @twobombs! That helped me narrow it down - there was a bug in `setup.py`, where it was attempting to read and open from `requirements.txt` (even though it didn't need to). I've now fixed this in #53

**Comment by twobombs** [comment]
Would it be prudent to make the new release ( 0.50-dev ) avaliable on 
 https://pypi.org/project/PennyLane/ or does this work automatically by some trigger ?

**Comment by josh146** [comment]
I might make a quick bugfix release (0.4.1) :)

**Comment by twobombs** [comment]
Haven't seen a release yet on https://pypi.org/project/PennyLane/#history
So technically the bug hasn't been fixed in that the pip3 install now does work.

**Comment by co9olguy** [comment]
Fair enough @twobombs :) I'll reopen until the update is available via pip

**Comment by josh146** [comment]
HI @twobombs, the v0.4.1 bugfix release is now available on pip :slightly_smiling_face:
